"""add refund fields to payment model

Revision ID: a260af5c5bea
Revises: 34e333528e6b
Create Date: 2026-09-04 05:20:58.806204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a260af5c5bea'
down_revision: Union[str, Sequence[str], None] = '34e333528e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('refund_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('refund_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'refund_reason')
    op.drop_column('payments', 'refund_id')
    # ### end Alembic commands ###
